### ISSUE TITLE
hex

### ISSUE THREAD

**Issue by lurchpop** [radial-color-picker/vue-color-picker#17]
would be great if it exposed a .hex property. yes, it's in the faq that hsl is better. but i want hex. that's what my app expects.

**Comment by rkunev** [comment]
Here are 2 ways you could get from HSL to HEX:
1. Using [parse-color](https://www.npmjs.com/package/parse-color)
2. Rolling your own converter - [gist](https://gist.github.com/rkunev/d1c35b1b56579663358092112c42b51e)

**Comment by lurchpop** [comment]
@rkunev i get it's possible to convert. just saying it'd be easier if this library did it without adding a dependency or 40 lines of code.

**Comment by rkunev** [comment]
Sure, I understand, but users who expect an HSL color model will have to download and execute extra code that they don't need at all.
