### ISSUE TITLE
A sample documentation of implementing in Nuxt.js

### ISSUE THREAD

**Issue by SwapnilSoni1999** [radial-color-picker/vue-color-picker#19]
Would be nice if you put some documentation of implementing in nuxt
thanks.

**Comment by rkunev** [comment]
Docs already cover that - https://radial-color-picker.github.io/vue-color-picker/guide/getting-started.html#nuxt-module.

### tl;dr:
1. Install the NPM package with `yarn add` or `npm install`
2. Add the module to `nuxt.config.js`
3. You can now use the color picker directly in any `.vue` file
```vue
<color-picker v-bind="color" @input="onInput" />
```
