### ISSUE TITLE
Color pickers don't work when placed close to each other/

### ISSUE THREAD

**Issue by ranashadab** [radial-color-picker/vue-color-picker#23]
**Describe the bug**
When we place multiple color pickers close to each other, specifically when the rotator can possibly overlap the ripples of other color pickers, we can't open/close other color pickers because the rotator is essentially blocking the ripple of last sibling color picker.  

**To Reproduce**
[Use this codepen snippet](https://codepen.io/ranashadab/pen/OJqVrwo)
You'll see only the last one can be opened or closed. other stay open always.

**Expected behavior**
It makes sense to block adjacent ripples if a rotator is overlapping them. But when we close the rotator, the sibling ripple should be clickable.
**Screenshots**
Only the last color picker can be opened or closed, other are blocked.
![image](https://github.com/radial-color-picker/vue-color-picker/assets/38768540/65bddb07-e56f-4208-a3d0-85265a4caa65)

**Comment by rkunev** [comment]
Okay, that's something that could be supported. Just to make sure we're on the same page - is this what you're after? https://codepen.io/rkunev/pen/poYgLPe

In the linked Codepen you'll find 2 instances of the color picker and the second instance covers the first one partially. When the second instance is collapsed then you can "click through" it and so you can interact with the picker behind.

**Comment by ranashadab** [comment]
Hey, @rkunev 
yeah that's exactly what I was trying,

**Comment by rkunev** [comment]
Alright, I'll cook up a new release soon with the fix and some other changes, stay tuned.

**Comment by rkunev** [comment]
Released `v6.0.0` which includes the fix. Release notes are [here](https://github.com/radial-color-picker/vue-color-picker/releases).
