### ISSUE TITLE
Convert the color value

### ISSUE THREAD

**Issue by jjoek** [radial-color-picker/vue-color-picker#4]
Hey, 
After binding the value to a data property, I get something like "245.6286566344196" how then do I get the color in this value?

**Comment by rkunev** [comment]
Chris Coyier's [article](https://css-tricks.com/hsl-hsla-is-great-for-programmatic-color-control/) on CSS Tricks about HSL/HSLA is a good starter. MDN has a great [resource](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#HSL_colors) about color values on the web as well. 

If you get stuck, let me know and I'll gladly help you!
